/*
 * rcc.c
 *
 *  Created on: Nov 13, 2025
 *      Author: dobao
 */

#include "rcc.h"

/*
 * @brief	Lookup table mapping ::RCC_Reg_t to the actual register address
 * @warning	Array order must match the enum exactly
 *
 * @note	'const' keeps the table in FLASH; each **value** remains 'volatile' because
 * 			the hardware can change it asynchronously.
 */
static volatile uint32_t* const rccRegLookupTable[RCC_REG_COUNT] = {
		[RCC_CR] 		= RCC_GET_REG(RCC_CR),
		[RCC_PLL_CFGR] 	= RCC_GET_REG(RCC_PLL_CFGR),
		[RCC_CFGR] 		= RCC_GET_REG(RCC_CFGR),
		[RCC_CIR]		= RCC_GET_REG(RCC_CIR),

		[RCC_AHB1_RSTR]	= RCC_GET_REG(RCC_AHB1_RSTR),
		[RCC_AHB2_RSTR]	= RCC_GET_REG(RCC_AHB2_RSTR),
		[RCC_AHB3_RSTR] = RCC_GET_REG(RCC_AHB3_RSTR),

		[RCC_APB1_RSTR] = RCC_GET_REG(RCC_APB1_RSTR),
		[RCC_APB2_RSTR] = RCC_GET_REG(RCC_APB2_RSTR),

		[RCC_AHB1_ENR] = RCC_GET_REG(RCC_AHB1_ENR),
		[RCC_AHB2_ENR] = RCC_GET_REG(RCC_AHB2_ENR),
		[RCC_AHB3_ENR] = RCC_GET_REG(RCC_AHB3_ENR),

		[RCC_APB1_ENR] = RCC_GET_REG(RCC_APB1_ENR),
		[RCC_APB1_ENR] = RCC_GET_REG(RCC_APB1_ENR),

		[RCC_AHB1_LP_ENR] = RCC_GET_REG(RCC_AHB1_LP_ENR),
		[RCC_AHB2_LP_ENR] = RCC_GET_REG(RCC_AHB2_LP_ENR),
		[RCC_AHB3_LP_ENR] = RCC_GET_REG(RCC_AHB3_LP_ENR),

		[RCC_BDCR]		= RCC_GET_REG(RCC_BDCR),
		[RCC_CSR]		= RCC_GET_REG(RCC_CSR),
		[RCC_SSCGR]		= RCC_GET_REG(RCC_SSCGR),
		[RCC_PLL_I2S_CFGR]	= RCC_GET_REG(RCC_PLL_I2S_CFGR),
};


static const uint32_t RCC_VALID_BITS[RCC_REG_COUNT] = {
		[RCC_CR] = RCC_CR_RESERVED_Msk,
		[RCC_PLL_CFGR] = RCC_PLL_CFGR_RESERVED_Msk,
		[RCC_CFGR] = RCC_CFGR_RESERVED_Msk,
		[RCC_CIR] = RCC_CIR_RESERVED_Msk,

		[RCC_AHB1_RSTR] = RCC_AHB1_RSTR_RESERVED_Msk,
		[RCC_AHB2_RSTR] = RCC_AHB2_RSTR_RESERVED_Msk,
		[RCC_AHB3_RSTR] = RCC_AHB3_RSTR_RESERVED_Msk,

		[RCC_APB1_RSTR] = RCC_APB1_RSTR_RESERVED_Msk,
		[RCC_APB2_RSTR] = RCC_APB2_RSTR_RESERVED_Msk,

		[RCC_AHB1_ENR] = RCC_AHB1_ENR_RESERVED_Msk,
		[RCC_AHB2_ENR] = RCC_AHB2_ENR_RESERVED_Msk,
		[RCC_AHB3_ENR] = RCC_AHB3_ENR_RESERVED_Msk,

		[RCC_AHB1_LP_ENR] = RCC_AHB1_LP_ENR_RESERVED_Msk,
		[RCC_AHB2_LP_ENR] = RCC_AHB2_LP_ENR_RESERVED_Msk,
		[RCC_AHB3_LP_ENR] = RCC_AHB3_LP_ENR_RESERVED_Msk,

		[RCC_APB1_LP_ENR] = RCC_APB1_LP_ENR_RESERVED_Msk,
		[RCC_APB2_LP_ENR] = RCC_APB2_LP_ENR_RESERVED_Msk,

		[RCC_BDCR] = RCC_BDCR_RESERVED_Msk,
		[RCC_CSR] = RCC_CSR_RESERVED_Msk,
		[RCC_SSCGR] = RCC_SSCGR_RESERVED_Msk,
		[RCC_PLL_I2S_CFGR] = RCC_PLL_I2S_CFGR_RESERVED_Msk
};
















